server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      mvc:
        routes: # 라우팅 설정
          - id: backend-user
            predicates: # 라우팅 조건
              - Path=/api/user/**
            uri: lb://backend-user
            filters:
              - AddAuthenticationHeader
          - id: backend-alim
            predicates: # 라우팅 조건
              - Path=/api/alim/**
            uri: lb://backend-alim
            filters:
              - AddAuthenticationHeader
          - id: backend-post
            predicates:
              - Path=/api/post/**
            uri: lb://backend-post
            filters:
              - AddAuthenticationHeader
    config:
      enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

management:
  tracing:
    sampling:
      probability: 1.0 # 0.0 ~ 1.0 사이 값 (모든 요청을 트레이싱하려면1.0)

logging:
  pattern:
    level: "%5p [%X{traceId},%X{spanId}]" # 로그에 traceId, spanId 추가

jwt:
  header: Authorization
  secret-key: ${JWT_SECRET_KEY}