server:
  port: 8081

#spring:
#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            # 'my-backend-service'에 대한 인스턴스 정의
#            alim-service:
#              - service-id: alim-service
#                uri: http://localhost:8082
#              - service-id: alim-service
#                uri: http://localhost:8082

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/user
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create # 오직 테스트 환경에서만
    generate-ddl: true # 오직 테스트 환경에서만
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    config:
      enabled: false
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans

management:
  tracing:
    sampling:
      probability: 1.0 # 0.0 ~ 1.0 사이 값 (모든 요청을 트레이싱하려면1.0)

logging:
  pattern:
    level: "%5p [%X{traceId},%X{spanId}]" # 로그에 traceId, spanId 추가

jwt:
  expires-in: 86400 # 1day
  mobile-expires-in: 31536000
  tablet-expires-in: 31536000
  secret-key: ${JWT_SECRET_KEY}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 # 하트비트 간격 (기본30초)
    lease-expiration-duration-in-seconds: 30 # 만료 시간 (기본90초)
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/